### PR TITLE
fix(ui): added broken documentation link in login page

### PR DESCRIPTION
**Pull request by acollazog11**

### CODE REVIEW

**Review by dev-bre — CHANGES_REQUESTED** [review]
Please use a tabs (4spaces) indentation. Your PR is changing the indentation for the entire file

**Comment by acollazog11** [comment]
> Please use a tabs (4spaces) indentation. Your PR is changing the indentation for the entire file

Right!, I realized about that, but I was not sure what is the style guide in the project, others files like `App.tsx`, `Flags.tsx`, `Segments.tsx`, ... use a tab with 2 spaces indentation.
If the rule is 4 spaces, I can update it, but at some point it should be defined with  eslint and/or prettier to avoid this for all contributors.

**Comment by dev-bre** [comment]
Good point. Would you be interested in working on it and consolidate? The repo already uses Eslint. So it should be a matter of adding prettier and configure it properly.

Would you be interested in it?

**Comment by acollazog11** [comment]
Sounds good! 
I will update the PR. Then I can start working on configure Eslint and Prettier, I think that only with Eslint is enough to avoid adding other libs. So we can create a new issue for that and define which rules we want to add. I can write few rules in the issue as a start point.

**Comment by acollazog11** [comment]
@dev-bre updated!! take a look now!

**Comment by dev-bre** [comment]
@acollazog11 looks good good idea on replacing the button with a link!

**Review by dev-bre — APPROVED** [review]

**Pull request merged**
